### ISSUE TITLE
System.MissingMethodException: Method not found error.

### ISSUE THREAD

**Issue by halukuzuner** [russgreen/FileUpgrader#2]
I compiled in Microsoft Visual Studio Community 2022 for Revit 2025. It return error as below. Is it because of my system or a potential error?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'System.Security.AccessControl.DirectorySecurity System.IO.DirectoryInfo.GetAccessControl()'.
   at ADNPlugin.Revit.FileUpgrader.UpgraderForm.SearchDir(DirectoryInfo sDir, Boolean first)
   at ADNPlugin.Revit.FileUpgrader.UpgraderForm.btnUpgrade_Click(Object sender, EventArgs e) in C:\Users\haluk.uzuner\Downloads\FileUpgrader-master\Source\UpgraderForm.cs:line 513
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by russgreen** [comment]
UpgraderForm.cs doesn't exist in my solution??   I think you might be using this project instead https://github.com/acnicholas/FileUpgrader/

**Comment by halukuzuner** [comment]
Yes you are right. I was confused by file names.
